### ISSUE TITLE
undefined: "github.com/goxjs/glfw".Stencil

### ISSUE THREAD

**Issue by henrikcozza** [shibukawa/nanovgo#5]
web.go:37: undefined: "github.com/goxjs/glfw".Stencil

I changed glfw.Stencil to glfw.StencilBits in web.go sample.

**Comment by dmitshur** [comment]
This looks valid and should be easy to fix.

As I mentioned in https://github.com/goxjs/glfw/pull/7#issuecomment-160389896:

> Merged and applied the Depth -> DepthBits, Stencil -> StencilBits changes in [`b3b34e9`](https://github.com/goxjs/glfw/commit/b3b34e95345717a8145fbc02e487a90590d548ab). You'll want to update your code to use those.

@shibukawa, can you apply this fix?

**Comment by shibukawa** [comment]
Fix. Sorry for my late response.
